version: '3.2'
services:
  user_manager:
    tty: true
    container_name: user_manager
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JWT_KEY=0123456789ABCDEF0123456789ABCDEF
      - DB_HOST=user_base
      - DB_PORT=5432
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
    depends_on:
      pg_db:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - my-network

  product_manager:
    tty: true
    container_name: product_manager
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JWT_KEY=0123456789ABCDEF0123456789ABCDEF
      - DB_HOST=user_base
      - DB_PORT=5432
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
    depends_on:
      pg_db:
        condition: service_healthy
    ports:
      - 8081:8080
    networks:
      - my-network

  pg_db:
    container_name: user_base
    image: postgres:15
    environment:
      - POSTGRES_USER=stud
      - POSTGRES_PASSWORD=stud
      - PGDATA=/data/postgres
      - POSTGRES_DB=archdb
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d archdb -U stud"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - my-network

networks:
  my-network:
    driver: "bridge"
    external: false